apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-web
  template:
    metadata:
      labels:
        app: static-web
    spec:
      containers:
      - name: static-web-container
        image: static-web-app:v1       # Local image name
        imagePullPolicy: Never         # CRITICAL: Ensures K8s uses the local image
        ports:
        - containerPort: 80